// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVs9RxJkC2E5PcOKbpPY3fW2RTS0oapv0',
    appId: '1:816063479247:web:01fe635bd7bca945caa6ba',
    messagingSenderId: '816063479247',
    projectId: 'crop-health-check',
    authDomain: 'crop-health-check.firebaseapp.com',
    storageBucket: 'crop-health-check.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcoj_dnIAznKtCs7jHSTs3Q_i72DHYHn8',
    appId: '1:816063479247:android:490ffb347d91476ccaa6ba',
    messagingSenderId: '816063479247',
    projectId: 'crop-health-check',
    storageBucket: 'crop-health-check.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-88hLOy9XbZrbvCwkmcNiZiUE64A_-50',
    appId: '1:816063479247:ios:546f39d46e99f6dfcaa6ba',
    messagingSenderId: '816063479247',
    projectId: 'crop-health-check',
    storageBucket: 'crop-health-check.appspot.com',
    androidClientId: '816063479247-ec3aa4vc0ecqi2eqvg0ar1n03aus06b2.apps.googleusercontent.com',
    iosClientId: '816063479247-ug893c7c9d3mlrv01gj2jfbtph7p9p2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-88hLOy9XbZrbvCwkmcNiZiUE64A_-50',
    appId: '1:816063479247:ios:546f39d46e99f6dfcaa6ba',
    messagingSenderId: '816063479247',
    projectId: 'crop-health-check',
    storageBucket: 'crop-health-check.appspot.com',
    androidClientId: '816063479247-ec3aa4vc0ecqi2eqvg0ar1n03aus06b2.apps.googleusercontent.com',
    iosClientId: '816063479247-ug893c7c9d3mlrv01gj2jfbtph7p9p2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );
}
